language: c

arch:
  - amd64
  - arm64

matrix:
  - os: linux
    addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

dist: xenial

compiler:
  - clang

env:
  matrix:
  - BUILD_SYSTEM="autotools" CONFIGURE_OPTS=
  - BUILD_SYSTEM="autotools" CONFIGURE_OPTS=--enable-64-bit-words
  - BUILD_SYSTEM="cmake"     CONFIGURE_OPTS=
  - BUILD_SYSTEM="cmake"     CONFIGURE_OPTS=-DENABLE_64_BIT_WORDS=ON

before_install:
    - eval "${MATRIX_EVAL}"
    
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -y install gettext libtool-bin libogg-dev doxygen libxml2-utils w3c-sgml-lib; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update ; brew install libogg; fi

script:
  - if [[ "${BUILD_SYSTEM}" == "autotools" ]]; then ./autogen.sh && ./configure $CONFIGURE_OPTS && make && make check; fi
  - if [[ "${BUILD_SYSTEM}" == "cmake" ]]; then mkdir cmake-build && cd cmake-build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON $CONFIGURE_OPTS && cmake --build . && ctest -V; fi
  - if [ $TRAVIS_OS_NAME = linux ] && [ ${BUILD_SYSTEM} = "autotools" ]; then
      xmllint --valid --noout doc/html/*.html;
      xmllint --valid --noout doc/html/api/*.html;
    fi
